modLoader = "javafml"
loaderVersion = "[4.0.42,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "resoureexporter"
version = "${version}"
displayName = "resoureExporter"
authors = "guapi_exe"
description = '''
exporter your mods resources!
'''
#logoFile = ""

[[dependencies.resoureexporter]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resoureexporter]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resoureexporter]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "resoureexporter.mixins.json"
